teams:
- name: community
  maintainers:
  - ryjones
  members:
  - hendrikebbers
  - popowycz
  - dmueller2001
  - rbair23
  - awaiken
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - minyu66
  - thelinuxfoundation
repositories:
- name: governance
  teams:
    lf-staff: maintain
  visibility: public
- name: planning
  teams:
    community: maintain
    lf-staff: maintain
  visibility: private
