teams:
- name: community
  maintainers:
  - hendrikebbers
  - samswag
  members:
  - dmueller2001
  - popowycz
  - rbair23
  - travismccracken11
  - fakepaulbugeja
  - SimiHunjan
  - rwalworth
  - nathanklick
  - alex-kuzmin-hg
  - AlfredoG87
  - alikatamjani
  - allison-hashgraph
  - ohsnapandrew
  - anthony-swirldslabs
  - a-saksena
  - arlanharris
  - artemananiev
  - Ashe-Oro
  - atul-hedera
  - atulmahamuni
  - litt3
  - beeradb
  - bguiz
  - cweagans
  - CMiville42
  - dalvizu
  - david-bakin-sl
  - derektriley
  - diptimahamuni
  - dougvk
  - ed-marquez
  - edward-swirldslabs
  - edwin-greene
  - elijahlynn
  - ebadiere
  - Neurone
  - gregscullard
  - web3-nomad
  - iwsimon
  - isaac-swirldslabs
  - imalygin
  - VMN00B
  - jasperpotts
  - JeffreyDallas
  - jeromy-cannon
  - jnels124
  - joebxmoxx
  - jbair06
  - jsync-swirlds
  - justin-atwell
  - kfbr
  - Reccetech
  - poulok
  - kimbor
  - kfa-aguda
  - theekrystallee
  - lpetrovic05
  - lbaird
  - leninmehedy
  - povolev15
  - LionelChocron
  - quiet-node
  - acuarica 
  - lukelee-sl
  - Mark-Swirlds
  - mattp-swirldslabs
  - rustyShacklefurd
  - matteriben
  - mhess-swl
  - mx-swirldslabs
  - m-swirldslabs
  - Defigirlxo 
  - netopyr
  - tinker-michaelj
  - mb-swirlds
  - mgarbs
  - michielmulders
  - mgoelswirlds
  - Nana-EC
  - nathanklick
  - Neeharika-Sompalli
  - nirbosl
  - OlegMazurov
  - pathornteng
  - fakepaulbugeja
  - RaphaelMessian
  - rbair23
  - rwalworth
  - rbarkerSL 
  - rsinha
  - ryan-swirldslabs
  - sergmetelin
  - shezaan-hashgraph
  - SimiHunjan
  - steven-sheehy
  - tannerjfco
  - tolorukooba
  - thomas-swirlds-labs
  - tim-mchale
  - timo0
  - tomzhenghedera
  - olsentorfinn 
  - travismccracken11
  - ty-swirldslabs 
  - xin-hedera
- name: tsc
  maintainers:
  - hendrikebbers
  members:
  - popowycz
  - rbair23
  - stoqnkpL
  - Perseverance
  - lbaird
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - minyu66
  - thelinuxfoundation
- name: hiero-sdk-swift-maintainers
  maintainers:
  - rwalworth
  members:
  - izik
  - RickyLB
  - SimiHunjan
- name: hiero-sdk-go-maintainers
  maintainers:
  - 0xivanov
  members:
  - SimiHunjan
  - andrix10
  - rwalworth
- name: hiero-sdk-cpp-maintainers
  maintainers:
  - rwalworth
  members:
  - SimiHunjan
repositories:
- name: governance
  teams:
    lf-staff: maintain
    tsc: maintain
  visibility: public
- name: hiero-website
  teams:
    community: triage
    tsc: maintain
  visibility: public
- name: hiero
  teams:
    tsc: maintain
  visibility: public
- name: tsc
  teams:
    tsc: maintain
  visibility: public
- name: awesome-contributions
  teams:
    tsc: maintain
    community: triage
  visibility: public
- name: .github
  teams:
    tsc: maintain
  visibility: public
