teams:
- name: community
  maintainers:
  - hendrikebbers
  - samswag
  members:
  - dmueller2001
  - popowycz
  - rbair23
  - travismccracken11
  - fakepaulbugeja
  - SimiHunjan
  - rwalworth
  - nathanklick
  - alex-kuzmin-hg
  - AlfredoG87
  - alikatamjani
  - allison-hashgraph
  - ohsnapandrew
  - anthony-swirldslabs
  - a-saksena
  - arlanharris
  - artemananiev
  - Ashe-Oro
  - atul-hedera
  - atulmahamuni
  - litt3
  - beeradb
  - bguiz
  - cweagans
  - CMiville42
  - dalvizu
  - david-bakin-sl
  - derektriley
  - diptimahamuni
  - dougvk
  - ed-marquez
  - edward-swirldslabs
  - edwin-greene
  - elijahlynn
  - ebadiere
  - Neurone
  - gregscullard
  - web3-nomad
  - iwsimon
  - isaac-swirldslabs
  - imalygin
  - VMN00B
  - jasperpotts
  - JeffreyDallas
  - jeromy-cannon
  - jnels124
  - joebxmoxx
  - jbair06
  - jsync-swirlds
  - justin-atwell
  - kfbr
  - Reccetech
  - poulok
  - kimbor
  - kfa-aguda
  - theekrystallee
  - lpetrovic05
  - lbaird
  - leninmehedy
  - povolev15
  - LionelChocron
  - quiet-node
  - acuarica 
  - lukelee-sl
  - Mark-Swirlds
  - mattp-swirldslabs
  - rustyShacklefurd
  - matteriben
  - mhess-swl
  - mx-swirldslabs
  - m-swirldslabs
  - Defigirlxo 
  - netopyr
  - tinker-michaelj
  - mb-swirlds
  - mgarbs
  - michielmulders
  - mgoelswirlds
  - Nana-EC
  - nathanklick
  - Neeharika-Sompalli
  - nirbosl
  - OlegMazurov
  - pathornteng
  - fakepaulbugeja
  - RaphaelMessian
  - rbair23
  - rwalworth
  - rbarkerSL 
  - rsinha
  - ryan-swirldslabs
  - sergmetelin
  - shezaan-hashgraph
  - SimiHunjan
  - steven-sheehy
  - tannerjfco
  - tolorukooba
  - thomas-swirlds-labs
  - tim-mchale
  - timo0
  - tomzhenghedera
  - olsentorfinn 
  - travismccracken11
  - ty-swirldslabs 
  - xin-hedera
- name: tsc
  maintainers:
  - hendrikebbers
  members:
  - popowycz
  - rbair23
  - stoqnkpL
  - Perseverance
  - lbaird
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - minyu66
  - thelinuxfoundation
- name: hiero-sdk-swift-maintainers
  maintainers:
  - rwalworth
  members:
  - izik
  - RickyLB
  - SimiHunjan
- name: hiero-sdk-go-maintainers
  maintainers:
  - 0xivanov
  members:
  - SimiHunjan
  - andrix10
  - rwalworth
- name: hiero-project-committers
  maintainers:
    - nathanklick
  members:
    - 0xivanov
    - AlfredoG87
    - AliNik4n
    - Ashe-Oro
    - BartoszSolkaArianelabs
    - CMiville42
    - Coiling-Dragon
    - Daniel-K-Ivanov
    - ElijahLynn
    - Evdokia-Georgieva
    - IvanKavaldzhiev
    - Ivo-Yankov
    - JeffreyDallas
    - JivkoKelchev
    - Kirqkas
    - Mark-Swirlds
    - MiroslavGatsanoga
    - Nana-EC
    - Neeharika-Sompalli
    - Neurone
    - OlegMazurov
    - Petyo-Lukanov
    - RAMTO
    - RaphaelMessian
    - Reccetech
    - RickyLB
    - Sheng-Long
    - SimiHunjan
    - StanislawMazowieckiAriane
    - StoyanDrumev
    - SvetBorislavov
    - VMN00B
    - a-saksena
    - acuarica
    - agadzhalov
    - alex-kuzmin-hg
    - allison-hashgraph
    - amckay7777
    - anastasiya-kovaliova
    - andrewb1269hg
    - annamariyaivanova
    - anthony-swirldslabs
    - ar-conmit
    - arianejasuwienas
    - arrusev
    - artemananiev
    - ata-nas
    - attest08
    - atul-hedera
    - beeradb
    - bibitibooo1
    - bilyana-gospodinova
    - cweagans
    - dalvizu
    - david-bakin-sl
    - derektriley
    - devmab
    - dikel
    - dimitar-dinev
    - dimitrovmaksim
    - donaldthibeau
    - dougvk
    - dr20240304
    - ebadiere
    - ed-marquez
    - edward-swirldslabs
    - edwin-greene
    - ericleponner
    - failfmi
    - georg-getz
    - georgi-l95
    - georgiyazovaliiski
    - gregscullard
    - gsstoykov
    - hendrikebbers
    - ibankov
    - imalygin
    - instamenta
    - ivaylogarnev-limechain
    - ivaylonikolov7
    - iwsimon
    - izik1
    - janaakhterov
    - jasperpotts
    - jayv80
    - jeromy-cannon
    - jjohannes
    - jnels124
    - joan41868
    - jsync-swirlds
    - kacper-koza-arianelabs
    - kenthejr
    - kfa-aguda
    - kfbr
    - kimbor
    - konstantinabl
    - kselveliev
    - leninmehedy
    - litt3
    - lpetrovic05
    - lukelee-sl
    - maptuhec
    - matteriben
    - mattp-swirldslabs
    - mgarbs
    - mgoelswirlds
    - mhess-swl
    - michalrozekariane
    - michielmulders
    - mishomihov00
    - mmalik-al
    - mustafauzunn
    - mxtartaglia-sl
    - nadezhdapopovaa
    - natanasow
    - netopyr
    - nickeynikolovv
    - nirbosl
    - nistanimirov
    - norbert-kulus-arianelabs
    - ochikov
    - pathornteng
    - petreze
    - pjn82
    - pkaterskiLime
    - poulok
    - povolev15
    - quiet-node
    - rbair23
    - rbarkerSL
    - reachtobhavesh
    - rickyrodmac
    - rsinha
    - rustyShacklefurd
    - rwalworth
    - san-est
    - se7enarianelabs
    - sergmetelin
    - shezaan-hashgraph
    - steven-sheehy
    - stoqnkpL
    - stoyan-lime
    - stoyanov-st
    - svetoslav-nikol0v
    - svienot
    - tannerjfco
    - tdermendzhievv
    - theekrystallee
    - thenswan
    - thomas-swirlds-labs
    - tim-mchale
    - timo0
    - tinker-michaelj
    - tolorukooba
    - tomzhenghedera
    - ty-swirldslabs
    - victor-yanev
    - vtronkov
    - web3-nomad
    - xin-hedera
    - yiliev0
    - yosiftouma
repositories:
- name: governance
  teams:
    lf-staff: maintain
    tsc: maintain
  visibility: public
- name: hiero-website
  teams:
    community: maintain
    tsc: maintain
  visibility: public
- name: hiero
  teams:
    tsc: maintain
  visibility: public
- name: tsc
  teams:
    tsc: maintain
  visibility: public
- name: awesome-contributions
  teams:
    community: maintain
  visibility: public
- name: .github
  teams:
    tsc: maintain
  visibility: public
