teams:
- name: community
  maintainers:
  - hendrikebbers
  - samswag
  members:
  - dmueller2001
  - popowycz
  - rbair23
  - travismccracken11
  - fakepaulbugeja
- name: tsc
  maintainers:
  - hendrikebbers
  members:
  - popowycz
  - rbair23
  - stoqnkpL
  - Perseverance
  - lbaird
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - minyu66
  - thelinuxfoundation
repositories:
- name: governance
  teams:
    lf-staff: maintain
    tsc: maintain
  visibility: public
- name: website
  teams:
    community: maintain
    tsc: maintain
  visibility: public
- name: hiero
  teams:
    tsc: maintain
  visibility: public
- name: tsc
  teams:
    tsc: maintain
  visibility: public
- name: awesome-contributions
  teams:
    community: maintain
  visibility: public
- name: .github
  teams:
    tsc: maintain
  visibility: public
