teams:
- name: community
  maintainers:
  - hendrikebbers
  members:
  - popowycz
  - dmueller2001
  - rbair23
  - awaiken
  - samswag
- name: tsc
  maintainers:
  - hendrikebbers
  members:
  - popowycz
  - rbair23
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - minyu66
  - thelinuxfoundation
repositories:
- name: governance
  teams:
    lf-staff: maintain
    tsc: maintain
  visibility: public
- name: website
  teams:
    tsc: maintain
  visibility: public
- name: hiero
  teams:
    tsc: maintain
  visibility: public
- name: planning
  teams:
    community: maintain
    lf-staff: maintain
  visibility: private
